/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c5c5d3",
        "on-primary-container": "#90a8ff",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#dce1ff",
        "inverse-surface": "#2f3036",
        "on-error": "#ffffff",
        "on-tertiary-container": "#90a8ff",
        "surface-dim": "#dad9e1",
        "primary-fixed": "#dce1ff",
        "on-secondary": "#ffffff",
        "surface-tint": "#4059aa",
        "secondary-fixed": "#6bff8f",
        "error-container": "#ffdad6",
        "on-background": "#1a1b21",
        "tertiary-container": "#1e3a8a",
        "on-surface": "#1a1b21",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3fa",
        "secondary-container": "#6bff8f",
        "on-secondary-fixed-variant": "#005321",
        "outline": "#757682",
        "tertiary": "#00236f",
        "on-primary": "#ffffff",
        "surface-container": "#eeedf4",
        "on-primary-fixed": "#00164e",
        "on-primary-fixed-variant": "#264191",
        "background": "#faf8ff",
        "tertiary-fixed-dim": "#b6c4ff",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e3e1e9",
        "surface": "#faf8ff",
        "surface-variant": "#e3e1e9",
        "on-secondary-fixed": "#002109",
        "inverse-primary": "#b6c4ff",
        "primary-container": "#1e3a8a",
        "on-tertiary-fixed-variant": "#264191",
        "surface-container-high": "#e9e7ef",
        "surface-bright": "#faf8ff",
        "primary-fixed-dim": "#b6c4ff",
        "on-secondary-container": "#007432",
        "secondary": "#006e2f",
        "secondary-fixed-dim": "#4ae176",
        "on-tertiary-fixed": "#00164e",
        "on-surface-variant": "#444651",
        "inverse-on-surface": "#f1f0f7",
        "primary": "#00236f",
        "error": "#ba1a1a"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      keyframes: {
        "slide-up": {
          "0%": { transform: "translateY(100%)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
      },
      animation: {
        "slide-up": "slide-up 0.5s ease-out",
      },
    },
  },
  plugins: [],
}
